### ISSUE TITLE
Manifest for oskarstark/php-cs-fixer-ga:null

### ISSUE THREAD

**Issue by emodric** [OskarStark/php-cs-fixer-ga#103]
Hi, I saw that you now automatically provide a newest version of PHP CS Fixer, but I'm not sure how this is supposed to work. I get the following errors now with my unchanged config.

```
Pull down action image 'oskarstark/php-cs-fixer-ga:null'
  /usr/bin/docker pull oskarstark/php-cs-fixer-ga:null
  Error response from daemon: manifest for oskarstark/php-cs-fixer-ga:null not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 6.43[2](https://github.com/netgen-layouts/layouts-core/actions/runs/6095240765/job/16538389536#step:2:2) seconds before retry.
  /usr/bin/docker pull oskarstark/php-cs-fixer-ga:null
  Error response from daemon: manifest for oskarstark/php-cs-fixer-ga:null not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 5.4[3](https://github.com/netgen-layouts/layouts-core/actions/runs/6095240765/job/16538389536#step:2:3)8 seconds before retry.
  /usr/bin/docker pull oskarstark/php-cs-fixer-ga:null
  Error response from daemon: manifest for oskarstark/php-cs-fixer-ga:null not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
```

**Comment by OskarStark** [comment]
I tried to fix the workflow myself, let's see how things are going:
https://github.com/OskarStark/php-cs-fixer-ga/actions/runs/6096486361

**Comment by OskarStark** [comment]
Looks like it works somehow and is green, but no tag is created 🤷🏼‍♂️

**Comment by OskarStark** [comment]
Ah ok, No need for a tag or a release on GitHub yet, the docker image on docker hub gets created as latest, so this should work now.

I think it would be nice to also tag the correct version.

Will have a look next week 👍🏻

**Comment by emodric** [comment]
@OskarStark Is there something I need to do on my side, because it still fails, but now with a different error

https://github.com/netgen-layouts/layouts-core/actions/runs/6095387977/job/16668014443

Thanks!

**Comment by OskarStark** [comment]
Can you try "latest" as version string?

**Comment by emodric** [comment]
Works now, thanks! :+1:

**Comment by OskarStark** [comment]
Just for my understanding, `latest` works, while a dedicated version not, right?

**Comment by emodric** [comment]
Actually, it was not issue with the version, as it turns out, I forgot to let you know, as I was trying different formats, so I wasn't actually sure what really helped.

So I took a look at it again and the issue was using the old `uses` notation in action config:

```
-      - uses: OskarStark/php-cs-fixer-ga@master
+      - uses: docker://oskarstark/php-cs-fixer-ga
```

**Comment by OskarStark** [comment]
OK, but does this work?

```diff
- - uses: docker://oskarstark/php-cs-fixer-ga
+ - uses: docker://oskarstark/php-cs-fixer-ga:latest
```

and

```diff
- - uses: docker://oskarstark/php-cs-fixer-ga
+ - uses: docker://oskarstark/php-cs-fixer-ga:3.25.1
```

?

**Comment by OskarStark** [comment]
Thanks!
